### PR TITLE
LPD-39542, LPD-39938 | Add missing test for folders and fix move action

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

[LPD-39542](https://liferay.atlassian.net/browse/LPD-39542)
[LPD-39938](https://liferay.atlassian.net/browse/LPD-39938)

### Changes

Add necessary test in the [epic](https://liferay.atlassian.net/browse/LPD-11110) related to the [LPD-15320](https://liferay.atlassian.net/browse/LPD-15320). 
Also fix the bug when moving elements (https://github.com/liferay-page-management/liferay-portal/pull/16452/commits/9023766c8c3773b71660b75c0c07df1e5a225778).

## Test scenario 

1. Create multiple DPTs and Folders
2. Use the move action in the management toolbar

[Screencast from 2024-10-23 18-23-13.webm](https://github.com/user-attachments/assets/77a087b3-b877-4106-b20c-9b10c916ec17)

[LPD-39542]: https://liferay.atlassian.net/browse/LPD-39542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LPD-39938]: https://liferay.atlassian.net/browse/LPD-39938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LPD-15320]: https://liferay.atlassian.net/browse/LPD-15320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by liferay-page-management** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:page-management

**Comment by BarbaraCabrera** [comment]
ci:test:page-management-playwright

**Comment by ealonso** [comment]
Hey @BarbaraCabrera,

Could you please fix the SF in [e5d84ef](https://github.com/liferay-page-management/liferay-portal/pull/16452/commits/e5d84ef11f3bf05e286ea22b332987cfcbdd6f95)? Thera are a lot of SF errors in that commit

Regards,
Eudaldo

**Comment by ealonso** [comment]
see: https://github.com/liferay-page-management/liferay-portal/pull/16510

**Pull request closed without merging**
