### PR TITLE
LPS-155170 [App Pages] Allow selecting from Document Library

### PR DESCRIPTION
**Pull request by sandrodw3**
Dear frontend reviewer,

In order to test this, please use https://github.com/sandrodw3/liferay-portal/pull/479, that contains the backend part that is needed 🥰

Thank you!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
pf this is so bonico

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/119710

**Pull request closed without merging**
