### PR TITLE
LPS-179253 Integration tests for notifications when web content expires

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to story](https://issues.liferay.com/browse/LPS-179142)

Adds integration tests for the story

### CODE REVIEW

**Review by lfbesada — APPROVED** [review]
Amazing ❤️

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1357401_3940

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
