### PR TITLE
LPD-42903  Allow Basic Get operations for Page Specifications nested fields

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-42903

This PR is sent for review of LPD-42903's commits. It also includes the dependent commits from [LPD-41551](https://github.com/brianchandotcom/liferay-portal/pull/156535) which need to be merged first.

[LPD-41551]: https://liferay.atlassian.net/browse/LPD-41551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by liferay-page-management** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
Putting it on-hold until https://github.com/brianchandotcom/liferay-portal/pull/156535 is merged

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/156613

**Pull request closed without merging**
