### PR TITLE
LPD-41067 Change the reference from the Collection Display to the Object from ID to ClassName

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-41067

This PR comes from the review of https://github.com/liferay-page-management/liferay-portal/pull/16556

@icgsbr Thanks for your PR!

I’ve added a few commits to improve source formatting, performance, and testing coverage. Please, check them out.

However, I noticed this class is used as the collection referenced in the EVP site initializers and the site initializer test bundles.

image

I am concerned because I believe if we don't replace those usages, we might break something.

What do you think?

Thanks!

### CODE REVIEW

**Comment by liferay-page-management** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
Thanks a lot for your help @lfbesada!

> However, I noticed this class is used as the collection referenced in the EVP site initializers and the site initializer test bundles.

@icgsbr could you please do the same thing that was done in this [commit](https://github.com/brianchandotcom/liferay-portal/pull/156041/commits/50e918c8f7549ad6e75ba9da90fc5fe265fce435#diff-7d0cda9000f3c933246da090919b6c0f7e4126b9ae782b0cdeecfe72ec9fe4ecL616-R617)?

**Comment by icgsbr** [comment]
Hi @carolmariaabb @lfbesada !

Just sent a new [PR](https://github.com/liferay-page-management/liferay-portal/pull/16566) with the requested changes.

Best regards.

**Comment by carolmariaabb** [comment]
ci:close

**Pull request closed without merging**
