### PR TITLE
LPS-198378 Move the Experience Selector inside the Performance tab

### PR DESCRIPTION
**Pull request by veroglez**
https://liferay.atlassian.net/browse/LPS-198378

Dear developer, 

this commit https://github.com/liferay-echo/liferay-portal/pull/13940/commits/4158d038f079fd9d8779cf70f929e9e5dfdf1dbc has to be reviewed by Frontend Infrastructure. When the PR will be reviewed set the label `on hold`.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
ci:test:sf

**Review by p2kmgcl — APPROVED** [review]
Nice :3

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by veroglez** [comment]
ci:stop

**Comment by veroglez** [comment]
see https://github.com/liferay-frontend/liferay-portal/pull/3743

**Pull request closed without merging**
