### PR TITLE
LPD-37711 Prevent NPE

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-37711

This code is covered with already existing layout page editor action command tests and the test that failed [here](https://github.com/liferay-page-management/liferay-portal/pull/16463#issuecomment-2437784950)

### CODE REVIEW

**Comment by liferay-page-management** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:page-management

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
