### PR TITLE
LPS-130821 Fix URLs in default site of not default instances

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-130821

Previous PR: https://github.com/liferay-echo/liferay-portal/pull/5938

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1357401_62

**Pull request closed without merging**
