### PR TITLE
LPD-43433 - FreeMarker syntax error in notifications with fields of related objects

### PR DESCRIPTION
**Pull request by abesousa**
### Already evaluated and approved original PR from [bpm](https://github.com/liferay-bpm/liferay-portal/pull/3946)

Ticket: https://liferay.atlassian.net/browse/LPD-43433

### Motivation

The user wants to create an email notification template using FreeMarker as editor 
to populate the email with data from a parent Object of an One to Many relationship.

### Proposed Solution

In the construction of the namespace for related fields, we replace the pound `#` symbol for 
underlines `_` to avoid a parser error with FreeMarker. This approach impacts the `FragmentEntryLink` table 
as it saves this value in its `editableValues` column. To maintain the integrity of current clients, we propose an upgrade process to update this value.

### Testing

To test the FreeMarker scenario, you can follow the instructions described in the ticket.
To test the scenario affected by the upgrade to the `FragmentEntryLink` table, follow these steps:

1. Edit a Portal Page adding a Collection Display;
2. Select a collection provider from a Custom Object that is a child of a One to Many relationship;
3. Add a Heading to the Collection Display;
4. Map the Heading to a field of the parent Object;

Without the upgrade, the Heading would not be able to render its correct value after the changes proposed 
in this PR.

### Request help

If you feel its necessary to amplify this solution to other tables you may think that would also be affected,  please let me know.

### CODE REVIEW

**Comment by liferay-page-management** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by abesousa** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
Hi @abesousa,
Thank you for the PR! 
I’ve been able to reproduce the error in the notification template following the steps outlined in the ticket, but I haven’t been able to replicate the issue on the pages you described in this PR description.
Could you please provide a video demonstrating the steps? 
Thank you in advance!
Best Regards

**Comment by abesousa** [comment]
Hi @lfbesada 

Here is the video:

https://github.com/user-attachments/assets/a846c45f-4411-43a9-8f80-5385a3885710

On this video, I create a Collection Display with a Heading while in the master branch. Then I apply the changes proposed in this PR and redeploy the `object-info-api` module (which has the replacement of pound symbols for underlines). After that, the Headings loses their references to its mapping fields. This is the issue we want to avoid by the proposed upgrade process.

Best Regards

**Comment by lfbesada** [comment]
@abesousa Thanks for the video! In its current state, this PR doesn't impact our components. I suggest BPM review it.

Also, I think [this commit](https://github.com/liferay-page-management/liferay-portal/pull/16760/commits/576fd4e43d5f754990991ca032503647a25dee2e) should use an if/else statement like this:

```
if (content.contains(StringPool.POUND)) {
    content = StringBundler.concat(
        ".data_model[\"", content, "\"]");
} else {
    content = StringBundler.concat(
        "${", content, ".getData()}");
}
```

Hope this helps!

Best regards

**Comment by carolmariaabb** [comment]
ci:close

**Pull request closed without merging**
