### PR TITLE
LPD-39563 Fix multiple Success Message in Form Container when using dropzone in a page

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Previous https://github.com/brianchandotcom/liferay-portal/pull/155297

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
> ### ❌ ci:test:sf - 0 out of 1 jobs passed in 25 minutes
> Click here for more details.
> #### Base Branch:
> Branch Name: [master](https://github.com/liferay/liferay-portal/tree/master)Branch GIT ID: [b3033ae367d39f24e7266bcc4ce388726cab038e](https://github.com/liferay/liferay-portal/commit/b3033ae367d39f24e7266bcc4ce388726cab038e)
> 
> #### Sender Branch:
> Branch Name: [LPD-39563](https://github.com/georgel-pop-lr/liferay-portal/tree/LPD-39563)Branch GIT ID: [49e414cdb9a681724a847a506acdfa5a42669604](https://github.com/georgel-pop-lr/liferay-portal/commit/49e414cdb9a681724a847a506acdfa5a42669604)
> 
> 0 out of 1jobs PASSED
> #### 1 Failed Jobs:
> * [test-portal-source-format](https://test-1-37.liferay.com/job/test-portal-source-format/10398/)
> 
> ##### For more details click [here](https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/10398/jenkins-report.html).
> format-source-files:
>      [java] Loading file:/opt/dev/projects/github/liferay-portal/portal-impl/classes/system.properties
>      [java] SLF4J: Class path contains multiple SLF4J bindings.
>      [java] SLF4J: Found binding in [file:/opt/dev/projects/github/liferay-portal/util-slf4j/classes/org/slf4j/impl/StaticLoggerBinder.class]
>      [java] SLF4J: Found binding in [jar:file:/opt/dev/projects/github/liferay-portal/lib/development/slf4j-simple.jar!/org/slf4j/impl/StaticLoggerBinder.class]
>      [java] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
>      [java] SLF4J: Actual binding is of type [com.liferay.util.slf4j.LiferayLoggerFactory]
>      [java] java.lang.Exception: Found 1 formatting issues:
>      [java] 1: ./modules/apps/account/account-service/src/main/java/com/liferay/account/internal/upgrade/v2_11_1/AccountRoleResourceUpgradeProcess.java expected:<... preparedStatement =[ connection.prepareStatement(
>      [java]         "update ResourceAction set actionId = ? where actionId = " +
>      [java] ]          "?")) \{
>      [java] 
>      [java]       pre...> but was:<... preparedStatement =[
>      [java]         connection.prepareStatement(
>      [java]           "update ResourceAction set actionId = ? where actionId = " +
>      [java]   ]          "?")) \{
>      [java] 
>      [java]       pre...>
>      [java] 
>      [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:473)
>      [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:302)
> [stopwatch] [run.batch.test.action: 23:20.538 sec]
>      [echo] The following error occurred while executing this line:
>      [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:448: The following error occurred while executing this line:
>      [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
>       [get] Getting: http://test-1-37/job/test-portal-source-format/10398//consoleText
>       [get] To: /opt/dev/projects/github/liferay-portal/20241021070255585.txt
>    [delete] Deleting: /opt/dev/projects/github/liferay-portal/20241021070255585.txt
>    [delete] Deleting: /opt/dev/projects/github/liferay-portal/null91969590.properties
> merge-test-results:
> [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
> [beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml

I don't have this on my local...

**Comment by ealonso** [comment]
@georgel-pop-lr it was already reviewed right?

**Comment by georgel-pop-lr** [comment]
> @georgel-pop-lr it was already reviewed right?

Yes, but I would like @lfbesada to have a look first

**Review by lfbesada — APPROVED** [review]

**Comment by ealonso** [comment]
@georgel-pop-lr last commit should be reviewed by Content Management Team

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
@georgel-pop-lr LGTM

**Comment by ealonso** [comment]
@georgel-pop-lr Could you please fix the rebase conflict and forward it?

**Comment by georgel-pop-lr** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
