### PR TITLE
[TS] LPS-154661

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by crodriguezy** [comment]
Hi team, do you think this is safe to be delivered to a customer? I'll have to adapt a similar idea to 7.3.x for them.

**Comment by ruben-pulido** [comment]
Hi @crodriguezy!
The fix looks good. I would only change the message to "unable-to-move-category-x-into-category-x-because-there-is-another-category-with-the-same-name-and-the-same-parent" or reuse the already existing key "there-is-another-category-with-the-same-name-and-the-same-parent" to have more consistent wording

**Comment by crodriguezy** [comment]
Also, about _"unable-to-move-category-x-into-category-x-because-there-is-another-category-with-the-same-name"_, we could be moving the category not into another category but into a vocabulary, so the message wouldn't apply to all scenarios.

What do you think @ruben-pulido ? Should we leave the message as it is?

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
