### PR TITLE
LPD-43562 Fix NullPointerException in LayoutModelListener during upgrade

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-43562

This issue arises when the module component LayoutModelListener executes before another module component, LayoutSiteNavigationMenuItemType, has been activated. By enforcing sequential activation, with LayoutSiteNavigationMenuItemType activating prior to LayoutModelListener, we ensure this timing conflict will not occur. 

While we cannot create a direct test case due to the lack of reproducible steps, **the affected logic is already covered by the test LayoutSiteNavigationMenuItemTypeTest.testAddToAutoMenuTrueToMenu**.

### CODE REVIEW

**Comment by liferay-page-management** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
@lfbesada Thank you for taking care of this for us! This looks fine to me.

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/156700

**Pull request closed without merging**
