### PR TITLE
LPD-42633 Restore default value

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:page-management-playwright

**Comment by sandrodw3** [comment]
ci:test:page-management-playwright

**Comment by ealonso** [comment]
ci:test:page-management-playwright

**Comment by sandrodw3** [comment]
ci:test:page-management-playwright

**Comment by sandrodw3** [comment]
ci:test:page-management-playwright

**Comment by ealonso** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/156591

**Pull request closed without merging**
