### PR TITLE
LPD-29534 Use current company instead of fragmentEntryLink company

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPD-29534

Hello, there is an issue when adding a new site in a publication in a virtual instance with db partition enabled. When creating the new site the 404 and 500 utility pages get added and the `fragmentEntryLink.getCompanyId()` returns the default company which leads to a CT transaction validation failure so I have proposed getting the companyId from the current company instead. This was caught with multiple functional tests in the "ci:test:publications-db-partition" test suite and can be also be seen here: [PublicationsSites#PublishSiteCreatedInPublication](https://testray.liferay.com/#/project/34754/routines/34756/build/24934322/case-result/24965140). Could you please check if this is ok or if it breaks anything? Thank you!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
@brookedalton Thank you for the fix!

Could you please add a test that verifies the use case you fix?

Thank you so much!

**Comment by brookedalton** [comment]
Hi @lfbesada! 

Our current test suite configuration runs the `publications-db-partition` suite once a week, and this issue is affecting roughly 30 functional tests so I'm not sure if we should add another test for this. The suite runs all of the existing publication poshi tests but configures the environment so db-partition is enabled in portal-ext.properties which is why the test history is not consistent.

Last suite: https://testray.liferay.com/#/project/34754/routines/34756/build/24934322 
Suite 2 weeks ago: https://testray.liferay.com/#/project/34754/routines/34756/build/13794452
Suite 3 weeks ago: https://testray.liferay.com/#/project/34754/routines/34756/build/9125808

Please let me know if this is ok, thanks!

**Comment by lfbesada** [comment]
Hi @brookedalton ,

Thank you very much for the details and your patience with this.

I have been able to locally reproduce the problem and I think I have found the root of the problem. The point is that the fragments, when they are contributed as is the case with OOTB, always set the companyId as the default one, and at some points, it is propagated to the fragmentEntryLinks. 

I think the solution must be the fragmentEntryLinks have their company set correctly.

I would like to have a little more time to find a robust solution to this problem since I think it affects other points as well. That is why I have assigned myself the ticket and I am going to work on its solution. I hope to have some updates on Monday.

Have a nice weekend! :heart: 

Best Regards

**Comment by brookedalton** [comment]
Thank you for taking a closer look at this! I'll close this PR, hope you have a nice weekend as well 🫶

**Pull request closed without merging**
