### PR TITLE
LPD-43154 SF

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by liferay-page-management** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
ci:test:page-management-playwright

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
@victorg1991 those tests need to be updated

[layout-content-page-editor-web/fragments.spec.ts](https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/497139/testReport/layout-content-page-editor-web_fragments.spec/ts)
[Localization Select Fragment › Allow selecting a language](https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/497139//testReport/layout-content-page-editor-web_fragments.spec/ts/Localization_Select_Fragment___Allow_selecting_a_language)
[layout-content-page-editor-web/formContainer.spec.ts](https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/497139/testReport/layout-content-page-editor-web_formContainer.spec/ts)
[Form Localization › Can translate form fields](https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/497139//testReport/layout-content-page-editor-web_formContainer.spec/ts/Form_Localization___Can_translate_form_fields)

**Pull request closed without merging**
