### PR TITLE
LPD-41551 Get endpoint for Page Specifications

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-41551

Dear reviewer :heart: 

This PR implements the endpoint `/sites/{siteExternalReferenceCode}/page-specifications/{pageSpecificationExternalReferenceCode}` for all types of page specifications, but it will fail for WidgetPageTemplate types because their layout does not belong to the site's group but to a separate group created for that layout. We will address this issue in future PRs.

Thank you!

### CODE REVIEW

**Comment by liferay-page-management** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
https://github.com/liferay-page-management/liferay-portal/pull/16654

**Pull request closed without merging**
