### PR TITLE
LPD-43020 Use the existing ScreenReaderAnnouncer

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Task separated from https://github.com/liferay-page-management/liferay-portal/pull/16641

### CODE REVIEW

**Comment by liferay-page-management** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:page-management-playwright

**Comment by georgel-pop-lr** [comment]
ci:reevaluate:1307401_10518

**Comment by ealonso** [comment]
ci:test:page-management-playwright

**Comment by ealonso** [comment]
@sandrodw3 @georgel-pop-lr we are doing changes in site-navigation and it is part of other team, so we need to mention this team or send the pr. It is also valid adding a comment in slack.

**Comment by georgel-pop-lr** [comment]
> Task separated from #16641

@liferay-page-management Could you please review this?

**Comment by ealonso** [comment]
@georgel-pop-lr the ownership of site-navigation is the Site Management Team, not the Content Management Team

**Comment by georgel-pop-lr** [comment]
> @georgel-pop-lr the ownership of site-navigation is the Site Management Team, not the Content Management Team

Yes, I update it. https://liferay.slack.com/archives/CLUBRGT42/p1733156585819289

**Comment by jonathanmccann** [comment]
@georgel-pop-lr This looks fine, thanks for mentioning us.

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward:force

**Pull request closed without merging**
