### PR TITLE
LPD-43768  Remove Release Feature Flag

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
Remove Release Feature Flag for _**LPD-10727 Support Multistep Experiences In The Page Editor**_

### CODE REVIEW

**Comment by liferay-page-management** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
@BarbaraCabrera you need to include the buildLang, also there is a dependency in playwright tests of LPD-10727

**Comment by BarbaraCabrera** [comment]
ci:test:page-management

**Comment by BarbaraCabrera** [comment]
ci:test:page-management

**Comment by ealonso** [comment]
ci:test:page-management

**Comment by BarbaraCabrera** [comment]
ci:test:page-management

**Comment by BarbaraCabrera** [comment]
ci:test:page-management

**Comment by BarbaraCabrera** [comment]
ci:test:page-management

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:test:page-management

**Comment by ealonso** [comment]
see: https://github.com/liferay-page-management/liferay-portal/pull/16741

**Pull request closed without merging**
