### PR TITLE
LPD-40356 Only hide old menu if portlet doesn't have custom options

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by liferay-page-management** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
ci:test:page-management

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
@sandrodw3 I need to fix the integration test

**Comment by ealonso** [comment]
see: https://github.com/liferay-page-management/liferay-portal/pull/16483

**Pull request closed without merging**
