### PR TITLE
LPD-45005 Add removed variable @Reference in LPS-204189 9be51f304d3ff…

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
…12bc69b7dfb22bdd2822de3802c

Not possible to add a test case as this only occurs with client database.

### CODE REVIEW

**Comment by liferay-page-management** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by georgel-pop-lr** [comment]
ci:stop

**Comment by georgel-pop-lr** [comment]
ci:forward

**Pull request closed without merging**
