### PR TITLE
 LPS-180171 Remove asset category properties value's validation

### PR DESCRIPTION
**Pull request by YurenaC**
Motivation
=======
[Link to ticket](https://issues.liferay.com/browse/LPS-180171)

Bug fixing: Currently, when you try to save an asset property with a value containing special character you get an error.

Proposed Solution
========
Remove the asset category properties value's validations to allow our clients to use the special characters there (you can see a list of those special characters in  AssetHelper file)

Steps to Verify
========

1) Create a category
2) Add a property to the category:

**Key**: URL
**Value**: https://someurl.com/

**Expected result:** The category is saved
**Actual result:** "Error: Please enter a valid property value. "

Commits
========
- LPS-180171 Remove asset category properties value's validation
- LPS-180171 Adding test for asset category properties value validation's removal

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:stop

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
Hi @ruben-pulido @jkappler @lfbesada,
I'd like to get your thoughts regarding this change as I'm not sure if can cause collateral damage elsewhere 

Thanks!

**Comment by YurenaC** [comment]
Proceed to close it as some security issues need to be addressed

**Pull request closed without merging**
