### PR TITLE
LPD-41919 Implement Site Pages Basic POST operations for Page Specification

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-41919

This PR is specifically for LPD-41919 but incorporates commits from other tickets to prevent conflicts:

- LPD-43800 and LPD-43460 are merged, awaiting merge into master.
- LPD-42539 is pending review [here](https://github.com/brianchandotcom/liferay-portal/pull/156896).

### CODE REVIEW

**Comment by liferay-page-management** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
see https://github.com/liferay-page-management/liferay-portal/pull/16750

**Pull request closed without merging**
