### PR TITLE
LPD-44632 On Site templates only the Default theme can be used on a Display Page Template

### PR DESCRIPTION
**Pull request by DaniSzimko**
[JIRA TICKET](https://liferay.atlassian.net/browse/LPD-44632)

**Motivation**: Currently, we handle public and private layout sets separately in site templates, but we can only configure the behavior of the private layout set.

**Solution**: When configuring the look and feel of the private layout set in a site template, propagate the changes to both layout sets.

### CODE REVIEW

**Comment by liferay-page-management** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DaniSzimko** [comment]
ci:test:sf

**Review by lfbesada — APPROVED** [review]
@DaniSzimko Thanks for the PR :heart: 
LGTM!
Regards

**Comment by victorg1991** [comment]
Hey @DaniSzimko I've updated a bit the playwright test and sent it here: https://github.com/liferay-page-management/liferay-portal/pull/16799 :) 

Thanks for the pr!

**Pull request closed without merging**
