### PR TITLE
LPD-41393 Convert the Development Feature Flag to a Deprecation Feature Flag

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-41393

On Hold waiting for [LPD-40974 Inconsistent Deprecation Feature Flag Behavior in New Installations](https://github.com/brianchandotcom/liferay-portal/pull/156365)

### CODE REVIEW

**Comment by liferay-page-management** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:page-management

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:page-management

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
