### PR TITLE
LPD-42061 Add the deprecation feature flag to Featured Content Fragment Set

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPD-42061)

### Changes

Add the deprecation label to the Featured Content Fragment Set

#### Case 1
1. Go to the page editor and go to the edit view.
2. Look for the deprecated label in the Featured Content Fragment Set.

#### Case 2
1. Go to fragments and look for the label in the Featured Content Fragment Set.
2. Click on the  Featured Content Fragment Set.
3. Check the button next to the name on top an the popover after clicking it.

https://github.com/user-attachments/assets/adb76026-b785-439f-9e70-6a572581b498

### CODE REVIEW

**Comment by liferay-page-management** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:playwright

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:playwright

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:playwright

**Comment by BarbaraCabrera** [comment]
ci:test:page-management

**Comment by BarbaraCabrera** [comment]
ci:test:page-management

**Comment by ealonso** [comment]
ci:test:page-management

**Comment by ealonso** [comment]
see: https://github.com/liferay-page-management/liferay-portal/pull/16687

**Pull request closed without merging**
