### PR TITLE
LPD-37704 It is not possible to cut and paste non-instantiable widgets

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-37704

cc: @georgel-pop-lr

### CODE REVIEW

**Comment by liferay-page-management** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:page-management

**Comment by ealonso** [comment]
Hey @lfbesada,

Could you please validate if https://github.com/liferay-page-management/liferay-portal/pull/16455#issuecomment-2436281271 are related with your changes?

Actually those ones are not failing on our routine.

**Comment by lfbesada** [comment]
Hi @ealonso I think they are not related to the changes added here, but I will re-run the test to ensure it. Thanks!

**Comment by lfbesada** [comment]
ci:test:page-management

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:stop

**Pull request closed without merging**
