### PR TITLE
LPD-43154 Use new method

### PR DESCRIPTION
**Pull request by sandrodw3**
cc @ealonso

### CODE REVIEW

**Comment by liferay-page-management** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
ci:test:page-management-playwright

**Comment by ealonso** [comment]
@sandrodw3 I'm fixing it right now, the failures are related with your changes in all-fields.json

**Comment by sandrodw3** [comment]
> @sandrodw3 I'm fixing it right now, the failures are related with your changes in all-fields.json

Ok! Also see in the Flaky tab that one of the new test failed the first time, I think we should make it more robust

**Comment by ealonso** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/156591

**Pull request closed without merging**
