### PR TITLE
LPS-178863 Simplify segments-experiment-web forms

### PR DESCRIPTION
**Pull request by p2kmgcl**
This PR is rebased onto this other one https://github.com/liferay-echo/liferay-portal/pull/11457 to avoid conflicts.

Although the initial goal of this PR is to standardize forms using formik, I did not find too much value in using this library for forms with just a couple of input elements.

Instead of applying formik, I have applied some SF and try to simplify the event handlers that are attached to the different form elements.

Also I have improved the form accessibility by moving the submit button inside the form itself, and adding the `required` HTML attribute were needed.

There shouldn't be any UI change.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
Started reviewing

**Review by claraizquierdo — APPROVED** [review]
Everything seems to be working fine. I added one commit with a small fix for a bug that I found while reviewing.

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
