### PR TITLE
LPD-42061 Use expect toPass

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by liferay-page-management** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
ci:test:page-management

**Comment by sandrodw3** [comment]
ci:stop

**Comment by sandrodw3** [comment]
ci:test:page-management

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
@sandrodw3 we need to upaste more tests

**Comment by sandrodw3** [comment]
> @sandrodw3 we need to upaste more tests

@ealonso which ones? Only the two Playwright ones related to localization are failing 🤔

**Comment by ealonso** [comment]
@sandrodw3 other teams are using featured content fragments

**Comment by ealonso** [comment]
see: https://github.com/liferay-page-management/liferay-portal/pull/16716

**Pull request closed without merging**
