### PR TITLE
LPS-177686 Mouse reorder

### PR DESCRIPTION
**Pull request by p2kmgcl**
Updated drag and drop behavior and hide ellipsis button (will be replaced with keyboard navigation) when `LPS-196420` is enabled.

screen-record-2023-09-20_08-58-1695193080

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141240

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
