### PR TITLE
LPS-203953 Show the rowchecker if the user is able to download the file

### PR DESCRIPTION
**Pull request by robertoDiaz**
Comes from https://github.com/liferay-lima/liferay-portal/pull/5015

In this case, to fix the DL issue, we had to move some logic from MVCAction to the Service layer, but the current AssetDisplayPageEntryFormProcessor API isn't service friendly (it has only a method that receives a PortletRequest.

I've overloaded this method in order to make it simpler use it in services.

This logic is in this commit: https://github.com/liferay-echo/liferay-portal/commit/ded5131c70d77323dfac3924240d4640ef51b7fc

The other commits are related with DL logic and has passed our review.

If you need any help, or if you have any question, please, tell me.

Thanks!!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
SF fixed (It was a rebase problem)

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/14773

**Pull request closed without merging**
