### PR TITLE
LPD-42400

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:page-management

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
Hey @veroglez,

Failures are related with your changes, removing 'navbar-text-truncate' makes those tests to fail. You need to look for it in poshi tests and playwright tests.

Poshi paths using this class:

- Form.path
- FrontendDataSet.path
- Wiki.path
- PopulateObjectFormsConfiguration.path
- ObjectCustomViews.path
- ObjectAdmin.path

**Comment by veroglez** [comment]
> Hey @veroglez,
> 
> Failures are related with your changes, removing 'navbar-text-truncate' makes those tests to fail. You need to look for it in poshi tests and playwright tests.
> 
> Poshi paths using this class:
> 
> * Form.path
> * FrontendDataSet.path
> * Wiki.path
> * PopulateObjectFormsConfiguration.path
> * ObjectCustomViews.path
> * ObjectAdmin.path
> 
> In playwright is used in:
> 
> * ObjectFieldsPage.ts

Thanks @ealonso! I'll take a look

**Comment by veroglez** [comment]
ci:test:page-management

**Comment by veroglez** [comment]
ci:stop

**Comment by veroglez** [comment]
ci:test:page-management

**Comment by veroglez** [comment]
ci:stop

**Comment by veroglez** [comment]
ci:stop

**Comment by veroglez** [comment]
ci:stop

**Comment by veroglez** [comment]
ci:test:page-management

**Comment by veroglez** [comment]
It seems that the failures are not related

**Comment by veroglez** [comment]
ci:forward

**Comment by veroglez** [comment]
ci:forward

**Comment by ealonso** [comment]
@veroglez you need to executed semantic versioning

[testSemanticVersioning[/apps/frontend-taglib/frontend-taglib-clay]](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1142049//testReport/com.liferay.semantic.versioning/SemanticVersioningTest/testSemanticVersioning__apps_frontend_taglib_frontend_taglib_clay_)

**Comment by veroglez** [comment]
ci:forward

**Comment by veroglez** [comment]
ci:stop

**Comment by veroglez** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
see: https://github.com/liferay-page-management/liferay-portal/pull/16628

**Pull request closed without merging**
